# Generated by Django 2.1.7 on 2019-07-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riVoiturage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traget',
            name='prix',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
            preserve_default=False,
        ),
    ]
