# Generated by Django 2.1.7 on 2019-04-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riVoiturage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traget',
            old_name='Chauffeur',
            new_name='chauffeur',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='voiture',
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='voiture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riVoiturage.Voiture'),
        ),
        migrations.AddField(
            model_name='traget',
            name='voiture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riVoiturage.Voiture'),
        ),
        migrations.AlterField(
            model_name='traget',
            name='clients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riVoiturage.Client'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carburant',
            field=models.CharField(choices=[('ESSENCE', 'ESSENCE'), ('GAZOILE', 'GAZOILE')], default='GAZOILE', max_length=10, null=True),
        ),
    ]
