# Generated by Django 2.1.7 on 2019-08-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riVoiturage', '0002_traget_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='traget',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traget',
            name='nbplace',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
